version: '3.8'

services:

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    # Application service
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        #   - ./vendor:/var/www/vendor
        #   - ./storage:/var/www/storage
        networks:
            - laravel
        depends_on:
            - db
    # PostgreSQL service
    db:
        image: postgres:13
        container_name: db
        restart: unless-stopped
        environment:
            POSTGRES_DB: clinica_app
            POSTGRES_USER: root
            POSTGRES_PASSWORD: Admin123
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

# Volumes for persisting data
volumes:
    pgdata:

# Networks for container communication
networks:
    laravel:
